"""empty message

Revision ID: e4bee6534bd3
Revises: 
Create Date: 2023-10-10 19:49:28.378280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4bee6534bd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('post_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###
